# Generated by Django 4.0.1 on 2022-01-21 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('url', models.URLField(blank=True, verbose_name='Personal Url')),
                ('text', models.TextField(verbose_name='Content')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Related Post')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
    ]
