# Generated by Django 4.0.1 on 2022-02-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_created'], 'verbose_name': 'Comment'},
        ),
    ]
